name: YTool.NET

on:
  push:
    branches: [ "test" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
    
    - name: Show Last tag1
      run: git tag -n --sort=-taggerdate | head -n 1
    
    - name: Last tag
      id: Last_tag
      run: echo '::set-output name=TAG_NAME::git tag -n --sort=-taggerdate | head -n 1'
      
    - name: Show Last tag2
      run: echo ${{ steps.Last_tag.outputs.TAG_NAME }}
