name: YTool.NET

on:
  push:
    branches: [ "test" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
       dotnet-version: 6.0.x
       
    - name: Restore dependencies
      run: dotnet restore YTool.App
      
    - name: Publish
      run: dotnet publish YTool.App -c Release --no-restore -o YTool.App/publish
      
    - name: Zip
      run: zip -r YTool.App.zip YTool.App/publish/
      
    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter: '[P|p]ublish:[v|V]\d(\.\d+){0,2}'
      
    - name: Show Changelog
      run: echo "${{ steps.changelog.outputs.changelog }}"

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}

          Document Website: https://raw.githack.com/jaywcjlove/changelog-generator/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html
      
    - name: Upload Release zip
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./YTool.App.zip
        asset_name: YTool.App.zip
        asset_content_type: application/zip
