name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
       dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore YTool.App
    - name: Build
      run: dotnet build YTool.App --no-restore
    - name: dotnet publish YTool.App
      run: dotnet publish YTool.App -c Release --no-restore -o YTool.App/publish
    - name: test ping host
      run: ping ${{ secrets.TXY_HOST }}
    - name: test telnet host
      run: telnet ${{ secrets.TXY_HOST }} 22
    - name: copy file to txy
      uses: appleboy/scp-action@master
      with:
       source: 'YTool.App/publish/*'
       host: ${{ secrets.TXY_HOST }}
       target: "/home/nginx-pord/html/YTool"
       port: 22
       username: ${{ secrets.TXY_LOGINNAME }}
       password: ${{ secrets.TXY_PASSWORD }}
