name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
       dotnet-version: 6.0.x
       
    - name: Restore dependencies
      run: dotnet restore YTool.App
      
    - name: Build
      run: dotnet build YTool.App --no-restore
      
    - name: Publish
      run: dotnet publish YTool.App -c Release --no-restore -o YTool.App/publish
      
    - name: Zip the Build
      run: zip -r YTool.App.zip YTool.App/publish/
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          YTool.App.zip
          LICENSE 
