name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ls
      run: ls
    - name: cd YTool.App
      run: cd \YTool.App;ls
    - name: ls
      run: ls
