name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: ls
      run: ls
    - name: cd YTool.App
      run: cd YTool.App 
    - name: ls
      run: ls
    - name: Restore dependencies
      run: dotnet restore
    - name: ls
      run: ls
    - name: cd YTool.App
      run: cd YTool.App 
    - name: ls
      run: ls
