name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
       dotnet-version: 6.0.x
       
    - name: Restore dependencies
      run: dotnet restore YTool.App
      
    - name: Build
      run: dotnet build YTool.App --no-restore
      
    - name: Publish
      run: dotnet publish YTool.App -c Release --no-restore -o YTool.App/publish
      
    - name: Zip the Build
      run: zip -r YTool.App.zip YTool.App/publish/
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
      
    - name: Upload Release zip
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./YTool.App.zip
        asset_name: YTool.App.zip
        asset_content_type: application/zip
