name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test ping host
      run: ping ${{ secrets.TXY_HOST }} -c 5
