name: YTool.NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    defaults:
      run:
        working-directory: /home/runner/work/YTool/YTool.App
    runs-on: ubuntu-latest
    steps:
    - name: ls
      run: ls
